# Generated by Django 5.0.3 on 2024-03-13 13:43

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Photo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50)),
                ("photos_image", models.ImageField(upload_to="images/%Y/%m/%d/")),
                ("photos_image200px", models.ImageField(upload_to="images/%Y/%m/%d/")),
                ("url", models.URLField()),
                ("description", models.TextField(max_length=1000)),
                ("likes_amount", models.IntegerField()),
                ("commemts_amount", models.IntegerField()),
                (
                    "publicate_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("add_date", models.DateTimeField(auto_now_add=True)),
                ("status", models.CharField(max_length=20)),
            ],
            options={
                "ordering": ["-add_date"],
                "indexes": [
                    models.Index(
                        fields=["-add_date"], name="api_photo_add_dat_0b7112_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Like",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="likes_author",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "photo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photo_like",
                        to="api.photo",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField(max_length=1000)),
                (
                    "publicate_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "parrent_comment",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comment",
                        to="api.comment",
                    ),
                ),
            ],
            options={
                "ordering": ["-publicate_date"],
                "indexes": [
                    models.Index(
                        fields=["-publicate_date"],
                        name="api_comment_publica_9527a4_idx",
                    )
                ],
            },
        ),
    ]
