# Generated by Django 5.0.3 on 2024-03-14 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_alter_photo_status"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="like",
            options={"ordering": ["created_date", "updated_date"]},
        ),
        migrations.AddField(
            model_name="like",
            name="created_date",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="like",
            name="updated_date",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
