# Generated by Django 5.0.3 on 2024-03-14 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_alter_like_options_like_created_date_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="photo",
            old_name="commemts_amount",
            new_name="comments_amount",
        ),
    ]
