# Generated by Django 5.0.3 on 2024-03-22 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_rename_commemts_amount_photo_comments_amount"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="photo",
            name="photos_image200px",
        ),
        migrations.RemoveField(
            model_name="photo",
            name="url",
        ),
        migrations.AddField(
            model_name="photo",
            name="thumbnail300px",
            field=models.ImageField(null=True, upload_to="images_thumbnail/%Y/%m/%d/"),
        ),
        migrations.AlterField(
            model_name="photo",
            name="comments_amount",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="photo",
            name="likes_amount",
            field=models.IntegerField(default=0),
        ),
    ]
