# Generated by Django 5.0.3 on 2024-03-22 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_remove_photo_photos_image200px_remove_photo_url_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="parrent_comment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="api.comment",
            ),
        ),
        migrations.AlterField(
            model_name="photo",
            name="comments_amount",
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name="photo",
            name="likes_amount",
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name="photo",
            name="thumbnail300px",
            field=models.ImageField(
                blank=True, null=True, upload_to="images_thumbnail/%Y/%m/%d/"
            ),
        ),
    ]
