# Generated by Django 5.0.3 on 2024-03-27 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_alter_comment_parrent_comment_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="photo",
            name="slug",
            field=models.SlugField(
                blank=True, max_length=75, null=True, unique_for_date="publicate_date"
            ),
        ),
        migrations.AlterField(
            model_name="photo",
            name="title",
            field=models.CharField(max_length=75),
        ),
    ]
